### ISSUE TITLE
поупражняйся в использовании различных компонентов bootstrap'а

### ISSUE THREAD

**Issue by dandgerson** [GregoryRubies/ptoject-test#1]
поупражняйся в использовании различных компонентов bootstrap'а. Используй различные классы и модули. ПОэкспериментируй с grid'ом пойми суть адаптивности. Вся информация есть на родном сайте http://getbootstrap.com/
и на http://www.w3schools.com/ tutorial'ax

**Comment by GregoryRubies** [comment]
Хорошо! днем буду упражняться !
